image: node:22-alpine

definitions:
  caches:
    pnpm: $HOME/.pnpm-store
  steps:
    - step: &build-test
        name: Build and Test
        caches:
          - pnpm
        script:
          - npm install -g pnpm
          - pnpm install
          - pnpm run build
        artifacts:
          - dist/**

    - step: &deploy-production
        name: Deploy to Production
        deployment: production
        caches:
          - pnpm
        script:
          - npm install -g pnpm
          - pnpm install
          - pnpm run build
          - echo "Deploying to production environment"
          # Add your production deployment commands here

    - step: &deploy-development
        name: Deploy to Development
        deployment: development
        caches:
          - pnpm
        script:
          - npm install -g pnpm
          - pnpm install
          - pnpm run build
          - echo "Deploying to development environment"
          # Add your development deployment commands here

    - step: &deploy-qa
        name: Deploy to QA
        deployment: qa
        caches:
          - pnpm
        script:
          - npm install -g pnpm
          - pnpm install
          - pnpm run build
          - echo "Deploying to QA environment"
          # Add your QA deployment commands here

pipelines:
  branches:
    master:
      - step: *build-test
      - step: *deploy-production
    
    desarrollo:
      - step: *build-test
      - step: *deploy-development
    
    qa:
      - step: *build-test
      - step: *deploy-qa
    
  pull-requests:
    '**':
      - step: *build-test